api/urls.py
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

from api.views import (
	ApiRootView,
	DetailHealthCheckApiView,
	SystemInfoApiView,
	HealthCheckApiView
)

app_name = 'api'

monitoring_patterns = [
	path('health/detailed/', DetailHealthCheckApiView.as_view(), name='health-detailed'),
	path('health/', HealthCheckApiView.as_view(), name='health'),
	path('system/', SystemInfoApiView.as_view(), name='system'),
]

auth_patterns = [
	path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
	path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

resources_patterns = [
	path('help/', include(('helpcenter.urls', 'helpcenter'), namespace='helpcenter')),
	path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
	path('categories/', include(('categories.urls', 'categories'), namespace='categories')),
	path('chapters/', include(('chapters.urls', 'chapters'), namespace='chapters')),
	path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
	path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
	path('fanfics/', include(('fanfics.urls', 'fanfics'), namespace='fanfics')),
]

forum_patterns = [
	path('forum/', include(('forum.urls', 'forum'))),
]

urlpatterns = [
	path('', ApiRootView.as_view(), name='root'),
	path('', include(monitoring_patterns)),
	path('', include(forum_patterns)),
	path('auth/', include(auth_patterns)),
	path('v1/', include(resources_patterns)),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap

from backend.sitemaps import FanficSitemap, CategorySitemap, SubCategorySitemap

from markdownx import urls as markdownx

sitemaps = {
	'fanfics': FanficSitemap,
	'categories': CategorySitemap,
	'subcategories': SubCategorySitemap,
	'flatpages': FlatPageSitemap,
}

urlpatterns = [
	path('admin/', admin.site.urls),
	path('api/', include(('api.urls', 'api'), namespace='api')),
	path('docs/', include(('backend.docs_urls', 'docs'), namespace='docs')),
	path('markdownx/', include(markdownx)),
	path('pages/', include('django.contrib.flatpages.urls')),

	path('offline.html', TemplateView.as_view(template_name="offline.html"), name='offline.html'),
]

urlpatterns += [
	path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

if settings.DEBUG and not settings.TESTING:
	urlpatterns += static(settings.MEDIA_URL,
						  document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL,
						  document_root=settings.STATIC_ROOT)

	# django debug toolbar
	if 'debug_toolbar' in settings.INSTALLED_APPS:
		urlpatterns += [
			path('__debug__/', include('debug_toolbar.urls')),
		]

helpcenter/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from helpcenter import views

from helpcenter.api.views import (
    FoireAuxQuestionsApiView,
    LexiqueApiView,
FlatPageApiView,
)

app_name = 'helpcenter'

router = DefaultRouter()

router.register(r'lexique', LexiqueApiView, basename='lexique')
router.register(r'faq', FoireAuxQuestionsApiView, basename='faq')
router.register(r'pages', FlatPageApiView, basename='pages')

urlpatterns = router.urls + [
    path('browse/title', views.browse_by_title, name='browse'),
    path('browse/title/<str:initial>', views.browse_by_title, name='browse_by_title'),
    path('search', views.SearchSubmitView.as_view(), name='search'),
    path('search-ajax-submit', views.SearchAjaxSubmitView.as_view(), name='search-ajax-submit'),
    path('foire-aux-questions', views.foire_aux_questions_view, name='foire_aux_questions'),
]

templates/help/base.html
{% load static %}
{% load i18n %}
<html lang="fr">
    <head>
    <meta charset="UTF-8">
    <title>Fanfiction {% block title %}{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="{% static 'styles/tailwind.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block styles %}
    {% endblock %}
    </head>
    <body id="page" class="container mx-auto px-4 bg-white">
        {% block content %}
        {% endblock %}
		
        <script src="{% static 'scripts/jquery.min.js' %}"></script>
        <script src="{% static 'scripts/intercooler-1.1.1.min.js' %}"></script>
        <script src="{% static 'scripts/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'scripts/infinite.min.js' %}"></script>
        {% block scripts %}
        {% endblock %}
		
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HDRHK2MFDJ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HDRHK2MFDJ');
</script>

templates/help/dico.html
{% extends "help/base.html" %}
{% load i18n %}

{% block content %}

<form id="form" role="form" action="{% url 'helpcenter:search' %}" method="post">
    {% csrf_token %}
    <input name="search"
           id="search"
           type="search"
           class="appearance-none block w-full bg-white text-teal-700 border border-teal-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-teal-500"

           placeholder="Rechercher une définition"
           ic-post-to="{% url 'helpcenter:search-ajax-submit' %}"
           ic-trigger-on="keyup changed"
           ic-trigger-delay="300ms"
           ic-target="#search-result-container"
           required pattern="\S+.*" />
</form>

<div id="search-result-container">

    {% include 'help/lexique.html' %}

</div>



{% endblock %}

templates/help/faq.html
{% extends "help/base.html" %}
{% load i18n %}
{% load cache %}
{% load markdown %}

{% block content %}

{% cache 500 questions %}
<div>
{% for question in questions %}
    {% ifchanged question.libelle %}<h3 class="mb-6 mt-4">{{ question.get_libelle_display }}</h3>{% endifchanged %}
    <button class="accordion">{{ question.question }}</button>
    <div class="panel">
        <div class="mt-4 mb-4">
        {{ question.reponse|markdown|safe }}
        </div>
    </div>
{% empty %}
    <p>{% trans 'Cette rubrique est vide' %}.</p>
{% endfor %}
</div>
{% endcache %}

{% endblock %}

{% block scripts %}
<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    }
  });
}
</script>
{% endblock %}

templates/help/lexique.html
{% load i18n %}

{#% for letter in 'abcdefghijklmnopqrstuvwxyz' %#}
    <a href="{#% url 'helpcenter:browse_by_title' initial=letter %#}"
       class="block mt-4 lg:inline-block disable-link lg:mt-0 text-teal hover:text-teal-darker mr-4"
    {#% if initial == letter %#}class="active"{#% endif%#}>
        {{ letter|upper }}
    </a>
{#% endfor %#}

{% for word in words %}
    <dl class="my-6">
        <dt class="font-semibold">{{ word.title }}</dt>
        <dd>{{ word.definition }}</dd>
    </dl>
{% empty %}
    <p>{% trans "Pas de définitions." %}</p>
{% endfor %}

templates/help/search_results.html
{% load i18n %}

{% if query %}
	<p>{% trans "Recherche" %}: <strong>{{ query }}</strong></p>
	<p>{{ title }}</p>

	{% if items %}

    	{% for item in items %}
        <dl class="my-6">
            <dt class="font-semibold">{{ item.title }}</dt>
            <dd>{{ item.definition }}</dd>
        </dl>
    	{% endfor %}

	{% endif %}
{% else %}
    {% include 'help/lexique.html' %}
{% endif %}

templates/help/search_submit.html
{% load i18n %}

{% if query %}
  {% include 'help/search_results.html' %}
{% else %}
  <p>{% trans "Pas de définition." %}</p>
{% endif %}